@ProjectE.Web_HostAddress = https://localhost:7194

@MusicID=9268891c-3aa8-4aff-ac5a-4454fa6aa672
@MusicID2=a8233ebb-a2cb-4ec5-bbc2-9da1a7a06cb4
GET {{ProjectE.Web_HostAddress}}/music/{{MusicID}}
Accept: application/json

###

POST {{ProjectE.Web_HostAddress}}/music
Accept: application/json
Content-Type: application/json

{
  "id": "a8233ebb-a2cb-4ec5-bbc2-9da1a7a06cb4",
  "songName": "My new cool song",
  "artist": "imon",
  "emoji": "Funk"
}
###

GET {{ProjectE.Web_HostAddress}}/music
Accept: application/json

###

@MusicID3=a8233ebb-a2cb-4ec5-bbc2-9da1a7a06cb4
DELETE {{ProjectE.Web_HostAddress}}/music/{{MusicID3}}
Accept: application/json

###

POST {{ProjectE.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "testing@gmail.com",
  "userName": "coolguy",
  "password": "MyP@ssword1!"
}

###
POST {{ProjectE.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "testing@gmail.com",
  "password": "MyP@ssword1!"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJ0ZXN0aW5nQGdtYWlsLmNvbSIsImV4cCI6MTcxNTI1NzI0NiwiaWF0IjoxNzE0NjUyNDQ2LCJuYmYiOjE3MTQ2NTI0NDZ9.TALXof9goaDo7ZTdECdW_cWP1fWygKx2XKnen8fOJaY

POST {{$projectUrl}}/favorites/song
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "0e4bc0a4-3e7a-4a7b-b98d-02402139e4ad",
  "name": "Careless Whisper",
  "artist": "George Michael",
  "emoji": "????"
}

###

GET {{ProjectE.Web_HostAddress}}/favorites
Accept: application/json
Authorization: Bearer {{token}}


###