@ProjectE.Web_HostAddress = https://localhost:7194

@MusicID=9268891c-3aa8-4aff-ac5a-4454fa6aa672
@MusicID2=a8233ebb-a2cb-4ec5-bbc2-9da1a7a06cb4
GET {{ProjectE.Web_HostAddress}}/music/{{MusicID}}
Accept: application/json

###

POST {{ProjectE.Web_HostAddress}}/music
Accept: application/json
Content-Type: application/json

{
  "id": "a8233ebb-a2cb-4ec5-bbc2-9da1a7a06cb4",
  "songName": "My new cool song",
  "artist": "imon",
  "emoji": "Funk"
}
###

GET {{ProjectE.Web_HostAddress}}/music
Accept: application/json

###

@MusicID3=a8233ebb-a2cb-4ec5-bbc2-9da1a7a06cb4
DELETE {{ProjectE.Web_HostAddress}}/music/{{MusicID3}}
Accept: application/json

###

POST {{ProjectE.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "testing@gmail.com",
  "userName": "coolguy",
  "password": "MyP@ssword1!"
}

###
POST {{ProjectE.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "testing@gmail.com",
  "password": "MyP@ssword1!"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJ0ZXN0aW5nQGdtYWlsLmNvbSIsImV4cCI6MTcxNTk1MDAxNiwiaWF0IjoxNzE1MzQ1MjE2LCJuYmYiOjE3MTUzNDUyMTZ9.mDbuR5TaiQRrExZCmAumgd9xi4nhHBaTVYjsk5CClVo

GET {{ProjectE.Web_HostAddress}}/music/emojis?firstEmoji=%F0%9F%91%91&secondEmoji=%F0%9F%91%91&thirdEmoji=%F0%9F%91%91
Accept: application/json
Authorization: Bearer {{token}}


###
POST {{$projectUrl}}/favorites/song
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "aa892533-6f75-4443-a047-3b6d4d0dea5e",
  "songName": "Radio Gaga",
  "artist": "Queen",
  "emoji": "??"
}

###

GET {{ProjectE.Web_HostAddress}}/favorites
Accept: application/json
Authorization: Bearer {{token}}


###